export const eventGenerator = (body: Object, pathParametersObject = {}) => {
  const request = {
    body: body ? JSON.stringify(body) : null,
    headers: {},
    multiValueHeaders: {},
    httpMethod: "",
    isBase64Encoded: false,
    path: "",
    pathParameters: pathParametersObject || null,
    queryStringParameters: pathParametersObject || null,
    multiValueQueryStringParameters: null,
    stageVariables: null,
    requestContext: {
      accountId: "",
      apiId: "",
      httpMethod: "",
      protocol: "",
      authorizer: null,
      identity: {
        accessKey: "",
        accountId: "",
        apiKey: "",
        apiId: "",
        apiKeyId: "",
        httpMethod: "",
        caller: "",
        cognitoAuthenticationProvider: "",
        cognitoAuthenticationType: "",
        cognitoIdentityId: "",
        cognitoIdentityPoolId: "",
        principalOrgId: "",
        sourceIp: "",
        user: "",
        userAgent: "",
        userArn: "",
        clientCert: {
          clientCertPem: "",
          serialNumber: "",
          subjectDN: "",
          issuerDN: "",
          validity: {
            notAfter: "",
            notBefore: "",
          },
        },
      },
      path: "",
      stage: "",
      requestId: "",
      requestTimeEpoch: 3,
      resourceId: "",
      resourcePath: "",
    },
    resource: "",
  };
  return request;
};
